### ISSUE TITLE
align with new features introduced in vscode-json-languageservice

### ISSUE THREAD

**Issue by pengx17** [redhat-developer/yaml-language-server#105]
Please refer to this: https://github.com/kpdecker/monaco-yaml/pull/5

If you feel like these updates are worthy, I will try to bring them into this repo as well. However I am afraid in the process of migration from JSON language service, I missed some key bug fixes for YAML syntax since there are no regression tests in our repo. I have go through some basic use cases (hover/validation) and it seems work fine though.

**Comment by JPinkney** [comment]
I definitely think those updates would be worthy. One of my goals was to bring the yaml language server back upto date with the JSON language server because that would resolve quite a few issues but I haven't had the time. If you're willing to bring them into this repo I can definitely give them a review. I skimmed through the PR you linked on that repo and it seems like everything should work. At most it would probably just be an issue of corner cases

**Comment by pengx17** [comment]
@JPinkney Hi Josh, I am still working on fixing migration issues in https://github.com/pengx17/monaco-yaml right now and I think it is kinda related. Some of the changes including:
- migrate monaco-json v2.0 as we have discussed
- adding linters (prettier to make sure all code styles are consistent)
- replace mocha with jest (Jest is)
- fixing unit tests
Apart from migration to v2.0, I believe all the others are worth doing as well from engineering perspective. Since I am more familiar with how language server works in monaco-editor, I am trying to make the service as stable as I can before moving them back to yaml-language-server.

Currently I am still struggling to fixing auto-completion right now, which turns out to be quite complex task. Other than that, I think this issue is ready to move forward. 

And at last, I am very happy to resolve some of the issues in vscode-yaml as well :D
