### ISSUE TITLE
Schema validator doesn't recognize Null literals

### ISSUE THREAD

**Issue by SupSuper** [redhat-developer/yaml-language-server#118]
Simple test case, make a schema with `"type": "null"`
Only the empty value is accepted as valid. The YAML null literals like `~` and `null` are rejected: https://yaml.org/type/null.html
This should be correctly supported by the parser: https://github.com/mulesoft-labs/yaml-ast-parser/blob/master/src/scalarInference.ts#L71

However, `"type": "string"` *does* accept Null literals, so this might be related to this fix: https://github.com/redhat-developer/yaml-language-server/issues/72

**Comment by zallek** [comment]
Any updates on that?
As @SupSuper said, the problem might be due to #72 as `null` token are expected to be parsed as null values and not string according to the YAML spec https://yaml.org/type/null.html

config
![Screen Shot 2020-02-14 at 12 21 57 PM](https://user-images.githubusercontent.com/1886834/74526871-a4c4cf80-4f24-11ea-87d3-04eb3e6ea755.png)

unexpected error:
![Screen Shot 2020-02-14 at 12 21 26 PM](https://user-images.githubusercontent.com/1886834/74526833-8959c480-4f24-11ea-89be-5888e3dbc116.png)

**Comment by timo-klarshift** [comment]
I am coming from here: https://github.com/redhat-developer/vscode-yaml/issues/277

I forked the yaml-language-server now and added tests for this issue. I also provided a fix which implements this: https://yaml.org/type/null.html

But I am in very doubt, if this will be accepted, as it could be that a lot of implementations actually rely on receiving the Null literals as strings. 

So I think the best solution would be to enable some configuration parameter to switch between those behaviors. But recording to the spec, I think the current implementation is just wrong here.

**Comment by timo-klarshift** [comment]
I created a PR with tests also.
I am not sure if that behavior will break something for the k8s folks. 
But in any case, we should stick to the YAML spec :)

https://github.com/redhat-developer/yaml-language-server/pull/241

**Comment by JPinkney** [comment]
Yeah, I think this should be switched back to the old behavior. I think in this case the kubernetes schema is actually wrong. If null is allowed in that case then the accepted types should be "string"/"null" not just "string". 

Even other validators online that I've found don't allow `null` when the type is string. When I implemented it originally I just thought they knew something that I didn't so I just figured they were right :man_shrugging:
