### ISSUE TITLE
Make auto completion use JSON Schema 7 parser

### ISSUE THREAD

**Issue by JPinkney** [redhat-developer/yaml-language-server#150]
Currently auto completion uses the JSON Schema 4 parser instead of the JSON Schema 7 parser.

There are a few things to do:
- [x] Make necessary modifications to JSON Schema 7 parser so auto completion will work with it
- [x] Make auto completion use the JSON Schema 7 parser
- [x] Remove JSON Schema 4 parser

**Comment by ToonvanStrijp** [comment]
@JPinkney For my own library I've implemented JSON schema 7 parser

I just changed all the code to compile and changed the parser to 7 etc. Feel free to use this code and improve it. I didn't test all features yet so that's something that still needs to be done.

[yamlCompletion.ts](https://gist.github.com/ToonvanStrijp/44b8f96f934ee18dce6a96b887beca64)

**Comment by JPinkney** [comment]
That's awesome! Do you mind submitting as a PR and I can work off your changes

**Comment by ToonvanStrijp** [comment]
@JPinkney sure no problem. I'll create one in a few hours or so.
