### ISSUE TITLE
`npm install yaml-language-server` has dependency duplicated in out/server/node_modules

### ISSUE THREAD

**Issue by mickaelistria** [redhat-developer/yaml-language-server#253]
I'm trying to fix an issue with Wild Web Developer because of too long file locations on Windows. The main culprit is yaml-language-server.
It looks like yaml-language-server duplicates all dependencies in out/server/node_modules (leading to long path names).
To reproduce it, just try `npm install -prefix . yaml-language-server`, and then browser to node_modules/yaml-language-server/out/server/node_modules, and the content from the top node_modules project is duplicated.

**Comment by mickaelistria** [comment]
Note that if from Wild Web Developer, I remove the extra deep `node_modules` folder, the language server still works. So IMO, it seems like this folder shouldn't be there in 1st place.

**Comment by JPinkney** [comment]
It looks like this: https://github.com/microsoft/vscode-languageserver-node/blob/master/server/bin/installServerIntoExtension

which gets ran here: https://github.com/redhat-developer/yaml-language-server/blob/master/package.json#L60

just copies everything fully, that's why its duplicated.

Apparently https://github.com/microsoft/vscode-languageserver-node/blob/master/server/bin/installServerIntoExtension is deprecated and this repo needs to be updated to whatever https://github.com/microsoft/vscode-extension-samples/tree/master/lsp-sample does.

Simple fix is to just add something like
```
rm -rf out/server/node_modules/
```
just after `npm run compile` here https://github.com/redhat-developer/yaml-language-server/blob/master/.travis.yml#L14

**Comment by JPinkney** [comment]
Should be fixed in 0.8.0
