### ISSUE TITLE
Provide a better way to contribute custom scheme

### ISSUE THREAD

**Issue by evidolob** [redhat-developer/yaml-language-server#267]
In Tekton extension we have a problem with contributing custom JSON Scheme for tekton resources.
The main problem is that K8s extension also add a very simple schemes for all CRD resources.
But YAML LS use only one, and we cannot change(and do not know) which.
To make a good tooling for Tekton we need to make sure that YAML LS uses JSON Schemes provided by tekton extension.

YAML LS has API which allows to modify parts of JSON Sheme, but that API works only with static schemes, and do not allow to modify custom schemes.

**Comment by JPinkney** [comment]
I'm not sure how we can solve this from the language server side. For any given file there can be multiple schemas matched from multiple different schema contributors. The only way to know "which one is best" is to find which schema matches the content the best, which is probably the issue where the YAML LS is only using one right now.

One way we might be able to go about this is to allow extensions to contribute different schemas depending on the vscode language mode. Then, if someone wants to have tekton specific support they can use the Tekton language mode in VSCode for their YAML files and the yaml language server will only use the contributed tekton schema.

Another alternative is to somehow make it so that users can override active schemas for the file somehow. This can be useful in a variety of cases, not just this one. But it would be a lot more manual of a solution

**Comment by evidolob** [comment]
> One way we might be able to go about this is to allow extensions to contribute different schemas depending on the vscode language mode. Then, if someone wants to have tekton specific support they can use the Tekton language mode in VSCode for their YAML files and the yaml language server will only use the contributed tekton schema.

I'm not sure how we can achieve that, as there are no limitation on filename or extension for Tekton resource, basically all tekton resources is k8s CRD. So we cannot determine what resource type represent some yaml file until we open and parse it.



> Another alternative is to somehow make it so that users can override active schemas for the file somehow. This can be useful in a variety of cases, not just this one. But it would be a lot more manual of a solution

That is not case for us, as we want to have 22 JSON Scheme in tekton extension(and it is only for latest api), I do not think that it will lead to good UI if user will forced to change scheme for every file.

Now we have workaround, we override function `requestCustomSchema` from `vscode-yaml` extension and throw away scheme URI from k8s extension. I was hopping that we may have a better way.
