### ISSUE TITLE
Provide completion text to insert without tabs, with only space

### ISSUE THREAD

**Issue by apupier** [redhat-developer/yaml-language-server#283]
tabs are not supported in yaml files.
Some IDEs are converting automatically such as VS Code Yaml but not all, like Eclipse client https://github.com/eclipse/wildwebdeveloper/issues/478

**Comment by apupier** [comment]
see https://github.com/redhat-developer/yaml-language-server/pull/272#issuecomment-655581898 for previous discussion on the subject

**Comment by evidolob** [comment]
We may use [workspace_configuration](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#workspace_configuration) `workspace/configuration` request to get preference value for `editor.tabSize`. At least it will work for VSCode. For other IDE it will depends on their implementation of `workspace_configuration`.
Or as alternative we may calculate `space` or `tab` for each line or yaml file.
And then use that value for snippet/completion generation.

**Comment by mickaelistria** [comment]
Since the YAML specification explicitly banishes tabs for indent ( https://yaml.org/spec/1.2/spec.html#id2777534 ), it can be seen as a that the LS can produce incorrect yaml by inserting tabs in any case.
The IDE shouldn't have to post-process the LS responses to make the file correct. They may post-process to make it more consistent with X or Y that's specific to the tool, but not to make the file conform to its spec/grammar.
So IMO, it's important to change that in the LS

My suggestion:
If no workspace_configuration is set, the LS should look at the file to infer the number of spaces for indent (looking at the number of spaces before the 1st char of the 2nd line can be one sufficient heuristic). In case the current file is empty, the LS should look in other known yaml files in the folder, in case nothing is available, it should pick the favourite convention of its developers.
