### ISSUE TITLE
Built in YAML Schemas are not working

### ISSUE THREAD

**Issue by JPinkney** [redhat-developer/yaml-language-server#356]
## Describe the bug

Based on the discovery in https://github.com/redhat-developer/vscode-yaml/issues/392#issuecomment-728380295 it looks like [YAML Schemas](https://yaml.org/spec/1.2/spec.html#Schema) aren't validating correctly.

## Expected Behavior

Flow-map: !!map { Clark: Evans, Ingy: döt Net, Oren: Ben-Kiki }

should validate without any errors

## Current Behavior

Flow-map: !!map { Clark: Evans, Ingy: döt Net, Oren: Ben-Kiki }

has unknown tag <tag:yaml.org,2002:map> error

## Steps to Reproduce

1. Paste `Flow-map: !!map { Clark: Evans, Ingy: döt Net, Oren: Ben-Kiki }` into document and observe the errors that occur

## Environment
- [ ] Windows
- [ ] Mac
- [X] Linux
- [ ] other (please specify)

**Comment by gorkem** [comment]
Is this protected by tests ?

**Comment by JPinkney** [comment]
No, the yaml-ast-parser doesn't have any tests for this so I'm currently writing them

**Comment by evidolob** [comment]
Hm, It may be related to my fix in yaml-ast-parser https://github.com/redhat-developer/yaml-ast-parser/pull/10
@JPinkney  ping me if you need some help on this.

**Comment by Emyrk** [comment]
The issue comes from here: https://github.com/redhat-developer/yaml-language-server/blob/master/src/languageservice/utils/parseUtils.ts#L101

Because the schema is passed into the ast library, the default is not used: https://github.com/redhat-developer/yaml-ast-parser/blob/master/src/loader.ts#L171

I think you'd have to extend the default schema with custom tags, rather than creating one from scratch here: https://github.com/redhat-developer/yaml-language-server/blob/master/src/languageservice/utils/parseUtils.ts#L70-L77

---
I did this in a fork and it works. I'm just not very typescript savy.

**Comment by gorkem** [comment]
Fixed with the new parser
