### ISSUE TITLE
Error with formatter in logs 

### ISSUE THREAD

**Issue by JPinkney** [redhat-developer/yaml-language-server#50]
```
[Info  - 13:47:47] Registering request handler for textDocument/formatting failed.
[Error - 13:47:47] (node:18851) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Unhandled method client/registerCapability
[Error - 13:47:47] (node:18851) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by mpanin** [comment]
Why this issue is closed?
I have pretty similar errors:
[Error - 11:11:32 AM] (node:17084) UnhandledPromiseRejectionWarning: #<Object>
[Error - 11:11:32 AM] (node:17084) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
[Error - 11:11:32 AM] (node:17084) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[Error - 11:11:32 AM] (node:17084) UnhandledPromiseRejectionWarning: #<Object>
[Error - 11:11:32 AM] (node:17084) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)

And I think it's the reason why yaml extension is not working in my vsc

**Comment by fhemberger** [comment]
Same issue.

```
[Error - 2:35:20 PM] (node:2171) UnhandledPromiseRejectionWarning: #<Object>
[Error - 2:35:21 PM] (node:2171) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
[Error - 2:35:21 PM] (node:2171) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[Error - 2:35:21 PM] (node:2171) UnhandledPromiseRejectionWarning: #<Object>
[Error - 2:35:21 PM] (node:2171) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
```
